### ISSUE TITLE
Refused to load the script

### ISSUE THREAD

**Issue by chandansgowda** [M27afk/proj-bookmarker_extension#3]
'https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js' because it violates the following Content Security Policy directive: "script-src 'self'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

**Comment by M27afk** [comment]
The CDN file is now included in the js folder and wont fetch the file in the web.
